apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: firewall-vnf
  namespace: kube-system
  labels:
    vnfType: firewall
spec:
  template:
    metadata:
      labels:
        name: firewall
    spec:
      containers:
      - name: firewall
        image: doonhammer/centosvnf:nostart
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "addshm -m 2084; vnf -f eth0"]
        securityContext:
          capabilities:
            add: ["ALL"]
        resources:
          limits:
            memory: 2000Mi
          requests:
            cpu: 1000m
            memory: 2000Mi
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: varlog
          mountPath: /var/log/vnf
        - name: varrun
          mountPath: /var/run/vnf
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: varlog
        hostPath:
          path: /var/log/vnf
      - name: varrun
        hostPath:
          path: /var/run/vnf
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
~                                          